name: liver-segmentation
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8  # Version depends on your GPU and compatibility
  - pytorch=2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - monai
  - matplotlib
  - numpy
  - pandas
  - pillow
  - nibabel
  - pyyaml
  - scikit-image
  - scikit-learn
  - tqdm