name: liver-segmentation
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - cudatoolkit=11.8   # CUDA Toolkit for GPU computation
  - cudnn=8.9          # Required for deep learning acceleration
  - pip:
      - monai
      - matplotlib
      - nibabel
      - pydicom
      - dicom2nifti
      - vedo
      - glob2
      - tqdm