name: liver-segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.4
  - pip
  - pip:
      - torch
      - monai
      - matplotlib
      - nibabel
      - pydicom
      - dicom2nifti
      - vedo
      - glob2